#branches:
#  except:
#    - gh-pages
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef install NCurses
  - zef install Term::Choose
  - zef install Term::Choose::Util
sudo: false







